const $=id=>document.getElementById(id);
const state={level:1,xp:0,xpNext:50,power:0,maxHp:100,hp:100,mapIndex:0,unlocked:[0],cleared:[],enemy:null,turn:0,stunned:false};
const screens={map:$('mapScreen'),battle:$('battleScreen'),reward:$('rewardScreen')};
const rows=[
 [{id:0,t:'fight',icon:'⚔️',name:'COMBATE',desc:'Enemigo normal'}],
 [{id:1,t:'fight',icon:'⚔️',name:'COMBATE',desc:'Enemigo normal'},{id:2,t:'elite',icon:'👹',name:'ÉLITE',desc:'Mejor recompensa'}],
 [{id:3,t:'event',icon:'❓',name:'EVENTO',desc:'Una decisión'} ,{id:4,t:'rest',icon:'💤',name:'DESCANSO',desc:'Recupera HP'},{id:5,t:'fight',icon:'⚔️',name:'COMBATE',desc:'Enemigo normal'}],
 [{id:6,t:'fight',icon:'⚔️',name:'COMBATE',desc:'Enemigo normal'},{id:7,t:'elite',icon:'👹',name:'ÉLITE',desc:'Riesgo / premio'}],
 [{id:8,t:'fight',icon:'⚔️',name:'COMBATE',desc:'Enemigo normal'} ,{id:9,t:'rest',icon:'💤',name:'DESCANSO',desc:'Recupera HP'}],
 [{id:10,t:'boss',icon:'👑',name:'JEFE',desc:'Guardián del bosque'}]
];
const links={0:[1,2],1:[3,4,5],2:[3,4,5],3:[6,7],4:[6,7],5:[6,7],6:[8,9],7:[8,9],8:[10],9:[10]};
function updateHud(){$('level').textContent=state.level;$('xp').textContent=state.xp;$('xpNext').textContent=state.xpNext;$('power').textContent=state.power}
function renderMap(){updateHud();const m=$('map');m.innerHTML='';rows.forEach((row,ri)=>{const r=document.createElement('div');r.className='row';row.forEach(n=>{const b=document.createElement('button');b.className=`node ${n.t} ${state.cleared.includes(n.id)?'done':''}`;b.disabled=!state.unlocked.includes(n.id)||state.cleared.includes(n.id);b.innerHTML=`<span class="icon">${n.icon}</span><span class="type">${n.name}</span><small>${n.desc}</small>`;b.onclick=()=>selectNode(n);r.appendChild(b)});m.appendChild(r)})}
function show(s){Object.values(screens).forEach(x=>x.classList.add('hidden'));s.classList.remove('hidden')}
function unlockFrom(id){(links[id]||[]).forEach(x=>{if(!state.unlocked.includes(x))state.unlocked.push(x)})}
function selectNode(n){state.mapIndex=n.id;if(n.t==='fight'||n.t==='elite'||n.t==='boss')startBattle(n);else if(n.t==='rest'){state.hp=Math.min(state.maxHp,state.hp+Math.ceil(state.maxHp*.3));state.cleared.push(n.id);unlockFrom(n.id);$('log').textContent='Descansas y recuperas parte de tu vida.';renderMap()}else if(n.t==='event'){const gain=15+Math.floor(Math.random()*16);state.xp+=gain;checkLevel();state.cleared.push(n.id);unlockFrom(n.id);alert(`Encuentras un antiguo altar. Ganas ${gain} XP.`);renderMap()}}
function startBattle(n){const elite=n.t==='elite',boss=n.t==='boss';const base=boss?{name:'GUARDIÁN ÓSEO',hp:140,dmg:17,xp:40,img:'assets/enemies/skeleton.svg'}:elite?{name:'GOBLIN ÉLITE',hp:105,dmg:15,xp:28,img:'assets/enemies/goblin.svg'}:(Math.random()<.5?{name:'GOBLIN',hp:70,dmg:10,xp:14,img:'assets/enemies/goblin.svg'}:{name:'ESQUELETO',hp:85,dmg:13,xp:18,img:'assets/enemies/skeleton.svg'});state.enemy={...base,maxHp:base.hp};state.turn=0;state.stunned=false;$('enemyImg').src=state.enemy.img;$('enemyName').textContent=state.enemy.name;show(screens.battle);updateBattle();renderAttacks();$('log').textContent=`Te enfrentas a ${state.enemy.name}.`}
const attacks=[['Golpe',18,'Daño directo'],['Tajo pesado',30,'Gran daño'],['Golpe aturdidor',14,'Aturde al enemigo'],['Segundo aliento',-22,'Recupera 22 HP']];
function renderAttacks(){const box=$('attacks');box.innerHTML='';attacks.forEach((a,i)=>{const b=document.createElement('button');b.className='attack';b.innerHTML=`${a[0]}<small>${a[1]<0?'Curación '+(-a[1]):a[1]+' daño'} · ${a[2]}</small>`;b.onclick=()=>playerAttack(i);box.appendChild(b)})}
function updateBattle(){const p=Math.max(0,state.hp/state.maxHp*100),e=Math.max(0,state.enemy.hp/state.enemy.maxHp*100);$('playerHpBar').style.width=p+'%';$('enemyHpBar').style.width=e+'%';$('playerHpText').textContent=`${state.hp} / ${state.maxHp} HP`;$('enemyHpText').textContent=`${state.enemy.hp} / ${state.enemy.maxHp} HP`;updateHud()}
function playerAttack(i){if(!state.enemy)return;const a=attacks[i];if(a[1]<0){state.hp=Math.min(state.maxHp,state.hp-a[1]);$('log').textContent='Recuperas 22 HP.'}else{const dmg=a[1]+state.power;state.enemy.hp=Math.max(0,state.enemy.hp-dmg);state.stunned=i===2;$('log').textContent=`Infliges ${dmg} de daño.`}updateBattle();if(state.enemy.hp<=0){winBattle();return}setTimeout(enemyTurn,450)}
function enemyTurn(){if(!state.enemy)return;if(state.stunned){state.stunned=false;$('log').textContent='El enemigo queda aturdido y pierde el turno.';return}const dmg=state.enemy.dmg;state.hp=Math.max(0,state.hp-dmg);$('log').textContent=`${state.enemy.name} te golpea por ${dmg}.`;updateBattle();if(state.hp<=0){setTimeout(()=>{alert('Has caído. La expedición vuelve a empezar.');resetRun()},250)}}
function winBattle(){const e=state.enemy;state.xp+=e.xp;checkLevel();state.cleared.push(state.mapIndex);unlockFrom(state.mapIndex);state.enemy=null;setTimeout(()=>{renderRewards(e);show(screens.reward)},350)}
function checkLevel(){while(state.xp>=state.xpNext){state.xp-=state.xpNext;state.level++;state.xpNext=Math.floor(state.xpNext*1.45);state.maxHp+=12;state.hp=state.maxHp}}
function renderRewards(enemy){const options=[['⚔️','Fuerza +5','Aumenta el daño de todos tus ataques.',()=>state.power+=5],['❤️','Vitalidad +25','Aumenta la vida máxima y te cura 25 HP.',()=>{state.maxHp+=25;state.hp=Math.min(state.maxHp,state.hp+25)}],['🩸','Curación +20','Recupera 20 HP ahora.',()=>state.hp=Math.min(state.maxHp,state.hp+20)]];const box=$('rewards');box.innerHTML='';options.forEach(o=>{const b=document.createElement('button');b.className='rewardBtn';b.innerHTML=`<strong>${o[0]} ${o[1]}</strong><span>${o[2]}</span>`;b.onclick=()=>{o[3]();renderMap();show(screens.map);if(enemy.name.includes('GUARDIÁN')){setTimeout(()=>{alert('¡Has derrotado al jefe! Nueva zona desbloqueada en la próxima versión.');},100)}};box.appendChild(b)})}
function resetRun(){state.level=1;state.xp=0;state.xpNext=50;state.power=0;state.maxHp=100;state.hp=100;state.mapIndex=0;state.unlocked=[0];state.cleared=[];state.enemy=null;renderMap();show(screens.map)}
renderMap();updateHud();
